CREATE TABLE transferencia
(
    id                      INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_transferencia      TIMESTAMP                            NOT NULL,
    valor                   DOUBLE PRECISION                     NOT NULL,
    tipo                    VARCHAR(15)                          NOT NULL,
    nome_operador_transacao VARCHAR(50),
    conta_id                INT,
    CONSTRAINT pk_transferencia PRIMARY KEY (id)
);

ALTER TABLE transferencia
    ADD CONSTRAINT FK_TRANSFERENCIA_ON_CONTA FOREIGN KEY (conta_id) REFERENCES conta (id_conta);
